### ISSUE TITLE
Git - Workflow

### ISSUE THREAD

**Issue by jstayton** [MonkDev/standards#3]
http://blogs.atlassian.com/2014/01/simple-git-workflow-simple/

**Comment by mcordell** [comment]
I've been using a combination of Shane's links for commit message formats and so far I like it. I use the base message laid out in the tbaggery link in Shane's comment. The other trick I picked up in his second link is to use one of the following keywords to start the summary:

* Add
* Modify
* Re-factor
* Fix
* Remove
* Tidy

The other thing I noticed is that by being intentional about a commit message in the body it forces the commits to be more atomic. If you have to explain 8 different side effects of your commit in the message, the commit is to big. As a side effect of this, I've noticed that I end up doing less `fixups` because I'm a bit more intentional about what is committed and when. I'm not for sure that the last point is true, but it has held for the last few weeks that I've been experimenting with this.

**Comment by shanebonham** [comment]
https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/

**Comment by jstayton** [comment]
https://guides.github.com/introduction/flow/index.html
